project:
  type: website

website:
  title: "General Genetics"
  sidebar:
    contents:
      - index.qmd
      - units/01_genomes.qmd
      - units/02_chromosomes.qmd
      - units/03_ploidy.qmd

format:
  html:
    toc: true
  pdf:
    toc: true
    geometry: margin=1in



