project:
  type: website

website:
  title: "General Genetics"
  sidebar:
    contents:
      - index.qmd
      - section: "Units"
        contents:
          - units/01_genomes.qmd
          - units/02_chromosomes.qmd
          - units/03_ploidy.qmd
          - units/04_Prions.qmd
          - units/05_population_genetics.qmd
      - section: "Practice & Exploration"
        contents:
          - activities/index.qmd

format:
  html:
    toc: true
  pdf:
    toc: true
    geometry: margin=1in



